apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-mcss
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-abcxzy
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: grafana-abcxzy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: grafana-abcxzy
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.cpu }}
            memory: {{ .Values.memory }}
          requests:
            cpu: {{ .Values.cpu }}
            memory: {{ .Values.memory }}
        env:
          - name: GF_AUTH_BASIC_ENABLED
            value: "true"
          - name: GF_SECURITY_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: grafana-mcss
                key: admin-username
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-mcss
                key: admin-password
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
        volumeMounts:
        - mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
          name: grafana-config
          readOnly: true
          subPath: datasources.yaml
        - mountPath: /etc/grafana/provisioning/dashboards/grafana-dashboard-provider.yaml
          name: grafana-config
          readOnly: true
          subPath: grafana-dashboard-provider.yaml
        {{- range $.Values.dashboards }}
        - mountPath: /var/lib/grafana/dashboards/{{ . }}
          name: grafana-config
          readOnly: true
          subPath: {{ . }}
        {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name}}
      serviceAccount: {{ .Values.serviceAccount.name}}
      securityContext: {}
      volumes:
      - configMap:
          name: grafana-config
        name: grafana-config
