{{- /*
based on
deployments/operator/samples/deviceplugin_v1_qatdeviceplugin.yaml
*/}}

apiVersion: deviceplugin.intel.com/v1
kind: QatDevicePlugin
metadata:
  name: {{ .Values.qat.metadata.name }}
  annotations:
    {{ toYaml .Values.qat.metadata.annotations | indent 4 }}
spec:
  image: {{ .Values.qat.spec.image }}
  {{- if .Values.qat.spec.initImage }}
  initImage: {{ .Values.qat.spec.initImage }}
  {{- end }}
  dpdkDriver: {{ .Values.qat.spec.dpdkDriver }}
  kernelVfDrivers:
    {{- range .Values.qat.spec.kernelVfDrivers }}
    - {{ . }}
    {{- end  }}
  maxNumDevices: {{ .Values.qat.spec.maxNumDevices }}
  logLevel:  {{ .Values.qat.spec.logLevel }}
  nodeSelector: {{ .Values.qat.spec.nodeSelector | toYaml | nindent 4 }}
---
{{ if eq .Values.qat.nodeFeatureRule true }}
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-dp-qat-device
spec:
  rules:
    - name: "intel.qat"
      labels:
        "intel.feature.node.kubernetes.io/qat": "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            device: {op: In, value: ["37c8", "4940"]}
            class: {op: In, value: ["0b40"]}
        - feature: kernel.loadedmodule
          matchExpressions:
            intel_qat: {op: Exists}
{{ end }}
