{{- if .Values.gaudi.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: intel-gaudi-resource-driver-role-binding
  namespace: {{ include "intel-gaudi-resource-driver.namespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "intel-gaudi-resource-driver.serviceAccountName" . }}
  namespace: {{ include "intel-gaudi-resource-driver.namespace" . }}
roleRef:
  kind: ClusterRole
  name: intel-gaudi-resource-driver-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}