# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: evi-hbase-zookeeper-pv
  labels:
    app: zookeeper
spec:
  capacity:
    storage: {{ required "A valid persistance.zookeeperSize is required!" .Values.persistance.zookeeperSize }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    namespace: {{ .Values.namespace.value }}
    name: data-{{ .Release.Name }}-zookeeper-0 
  storageClassName: {{ .Values.storageClass.name }}
  local:
    path: {{ required "A valid persistance.zookeeper.path is required!" .Values.persistance.zookeeper.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ required "A valid persistance.zookeeper.hostname is required!" .Values.persistance.zookeeper.hostname }}
