apiVersion: v2
name: intel-gaudi-resource-driver
description: A Helm chart for a Dynamic Resource Allocation (DRA) Intel Gaudi Resource Driver

type: application
version: 0.2.0
appVersion: "v0.2.0"
home: https://github.com/intel/helm-charts

dependencies:
  - name: node-feature-discovery
    alias: nfd
    version: "0.16.6"
    condition: nfd.enabled
    repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
