# Default values for intel-gaudi-resource-driver.
nameOverride: ""
namespaceOverride: "intel-gaudi-resource-driver"
fullnameOverride: ""
selectorLabelsOverride: {}

imagePullSecrets: []
image:
  repository: intel
  name: intel-gaudi-resource-driver
  pullPolicy: IfNotPresent
  tag: "v0.2.0"

serviceAccount:
  create: true
  annotations: {}
  name: intel-gaudi-resource-driver-service-account
  automount: true

kubeletPlugin:
  podAnnotations: {}
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  nodeSelector: {}
  #node-role.kubernetes.io/control-plane: ""
  affinity: {}
