# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
{{- if .Values.global.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace.value }}
{{ if .Values.global.namespace.istioInjection.create }}
  labels:
    istio-injection: enabled
{{ end }}
{{- end -}}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-evi-test-tool
  namespace: {{ .Values.global.namespace.value }}
  labels:
    account: evi-test-tool
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evi-test-tool
  namespace: {{ .Values.global.namespace.value }}
spec:
  selector:
    matchLabels:
      app: evi-test-tool
  replicas: 1
  template:
    metadata:
      labels:
        app: evi-test-tool
        sidecar.istio.io/inject: "{{ .Values.istioInjection }}"
        version: v1
    spec:
      nodeSelector:
        feature.node.kubernetes.io/cpu-cpuid.AVX512VNNI: 'true'
        feature.node.kubernetes.io/cpu-cpuid.AVX2: 'true'
      serviceAccountName: sa-evi-test-tool
      containers:
      - name: evi-test-tool
        image: "{{ .Values.image.repository }}:{{ .Values.image.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        ports:
        - containerPort: {{ .Values.image.port }}
        volumeMounts:
        #pod path
        - name: test-data
          mountPath: {{ .Values.persistent.podMountPath }}
        - name: config-evi-test-tool
          mountPath: {{ .Values.configMap.configTools.podMountPath }}
        - name: config-ai
          mountPath: {{ .Values.configMap.configAI.podMountPath }}
        - name: minio-secret
          mountPath: "/opt/evi_test_tool/credential/minio/"
          readOnly: true
        securityContext:
          # readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: "1"
            memory: 20Gi
          requests:
            cpu: 500m
            memory: 200Mi
      volumes:
      - name: test-data
        persistentVolumeClaim:
          claimName: pvc-evi-test-tool-data
      - name: config-evi-test-tool
        configMap:
          name: {{ .Values.configMap.configTools.value }}
      - name: config-ai
        configMap:
          name: {{ .Values.configMap.configAI.value }}
      - name: minio-secret
        secret:
          secretName: minio
