# Default values for intel-qat-resource-driver.
nameOverride: ""
namespaceOverride: "intel-qat-resource-driver"
fullnameOverride: ""
selectorLabelsOverride: {}

imagePullSecrets: []
image:
  repository: intel
  name: intel-qat-resource-driver
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

serviceAccount:
  create: true
  annotations: {}
  name: "intel-qat-resource-driver-service-account"
  automount: true

kubeletPlugin:
  podAnnotations: {}
  nodeSelector:
    feature.node.kubernetes.io/qat: "true"
    #node-role.kubernetes.io/control-plane: ""
  tolerations:
    # - key: node-role.kubernetes.io/master
    #   operator: Exists
    #   effect: NoSchedule
    # - key: node-role.kubernetes.io/control-plane
    #   operator: Exists
    #   effect: NoSchedule
    - key: "node.kubernetes.io/qat"
      operator: "Exists"
      effect: "NoSchedule"
  affinity: {}

nfd:
  enabled: false # change to true if NFD is not installed in cluster
  nameOverride: intel-qat-nfd
  enableNodeFeatureApi: true
