{{- /*
based on
deployments/operator/samples/deviceplugin_v1_dlbdeviceplugin.yaml
*/}}


apiVersion: deviceplugin.intel.com/v1
kind: DlbDevicePlugin
metadata:
  name: {{ .Values.name }}
  annotations: {{ toYaml .Values.annotations | nindent 4 }}
spec:
  image: "{{ .Values.image.hub }}/intel-dlb-plugin:{{ .Values.image.tag | default .Chart.AppVersion }}"
  initImage: "{{ .Values.initImage.hub }}/intel-dlb-initcontainer:{{ .Values.initImage.tag | default .Chart.AppVersion }}"
  logLevel: {{ .Values.logLevel }}
  nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 4 }}

---
{{ if eq .Values.dlb.nodeFeatureRule true }}
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-dp-dlb-device
spec:
  rules:
    - name: "intel.dlb"
      labels:
        "intel.feature.node.kubernetes.io/dlb": "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            device: {op: In, value: ["2710"]}
            class: {op: In, value: ["0b40"]}
        - feature: kernel.loadedmodule
          matchExpressions:
            dlb2: {op: Exists}
{{ end }}
