apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: multimodal-data-visualization
  name: multimodal-data-visualization
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
