# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
# Default values for ai-structuring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

global:
  namespace:
    create: false
    value: hce-ai
    istioInjection:
      create: false
  nodeAffinity:
    create: false
    key: kubernetes.io/hostname
    value: nodea

configMap:
  name: ai-structuring-cfg

image:
  repository: 10.67.108.226/hce/ai-structuring
  Version: master-20c2c999f53aad4c63c5d671ffe83e53f3e4f1a7
  pullPolicy: IfNotPresent
  containerPort: 8080

node:
  port: 31008

aiInference:
  addr: ai-inference.hce-ai
  port: 50051
