# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloaksecret
  namespace: {{ .Values.namespace.value }}
type: Opaque
data:
  db-password: {{ required "A valid secret.auth.dbPassword is required!" .Values.secret.auth.dbPassword }}
  admin-password: {{ required "A valid secret.auth.adminPassword is required!" .Values.secret.auth.adminPassword }}
