apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tac-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tac-leader-election-role
subjects:
- kind: ServiceAccount
  name: tac-svcact
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tac-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tac-proxy-role
subjects:
- kind: ServiceAccount
  name: tac-svcact
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tac-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tac-role
subjects:
- kind: ServiceAccount
  name: tac-svcact
  namespace: {{ .Release.Namespace }}
