apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: tac-metrics-service
  namespace: {{ .Release.namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.metricsPort }}
    targetPort: https
  selector:
    control-plane: controller-manager
