apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-deployment
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - image: "{{ .Values.mosquittoImage.repository }}:{{ .Values.mosquittoImage.tag | default .Chart.AppVersion }}"
        name: mqtt
        ports:
        - containerPort: 1883
          name: mqtt-port
        volumeMounts:
        - name: mqtt-config-file
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
      - name: mqtt-config-file
        configMap:
            name: evam-config-map