apiVersion: v1
kind: Service
metadata:
  name: mqtt-svc
  labels:
    app: mqtt
spec:
  type: NodePort
  ports:
    - port: 1883
      targetPort: 1883
      #nodePort: 31020
      protocol: TCP
      name: mqtt-port
  selector:
    app: mqtt