# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
{{- if .Values.global.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace.value }}
{{ if .Values.global.namespace.istioInjection.create }}
  labels:
    istio-injection: enabled
{{ end }}
{{- end -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: its-search-image-by-image
  namespace: {{ .Values.global.namespace.value }}
  labels:
    version: v1
  annotations:
    container.apparmor.security.beta.kubernetes.io/search-image-by-image: runtime/default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-image-by-image
      version: v1
  template:
    metadata:
      labels:
        app: search-image-by-image
        sidecar.istio.io/inject: "{{ .Values.istioInjection }}"
        version: v1
    spec:
      nodeSelector:
        feature.node.kubernetes.io/cpu-cpuid.AVX512VNNI: 'true'
        feature.node.kubernetes.io/cpu-cpuid.AVX2: 'true'
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      #- name: search-image-by-image
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.Version }}"
        args: ["--aiInference.addr=http://{{ .Values.aiInference.addr }}:{{ .Values.aiInference.port }}",
               "--fmMasterArchived.addr=http://{{ .Values.fmMasterArchived.addr }}:{{ .Values.fmMasterArchived.port }}/match",
               "--fmMasterOccurence.addr=http://{{ .Values.fmMasterOccurence.addr }}:{{ .Values.fmMasterOccurence.port }}/match",
              ] 
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        #- containerPort: 8088
        - containerPort: {{ .Values.image.port }}
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "100m"
            memory: 512Mi
        securityContext:
          # readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
