apiVersion: v1
kind: Service
metadata:
  name: {{ include "mc-ssr.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mc-ssr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "mc-ssr.selectorLabels" . | nindent 4 }}
