# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
# Default values for storage-rest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  create: false
  value: storage-rest
  istioInjection:
    create: false

image:
  repository: 10.67.108.226/hce/storage-rest
  Version: configsExpose
  pullPolicy: IfNotPresent

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "sa-storage-rest"

service:
  name: evi-storage-rest
  type: ClusterIP
  port: 9900
  targetPort: 9900

configMap:
  name: "storage-rest-cm"
  sqlDB:
    addr: evi-postgresql.postgresql
    port: 5432
  hdfs:
    nnService: "evi-hbase-hadoop-hdfs-nn"
    addr: "evi-hbase-hadoop-hdfs-nn.dev"
    port: "9870"
    archivePath: "/greenplum/vehicle_archive/"

# livenessProbe settings for deployment
liveness:
  path: "/v1/capture_source/districts"
  httpHeaders:
    name: Custom-Header
    value: Awesome
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 5

# secret settings for deployment
secret:
  secretName: storage-rest-secret
  auth:
    # secret.auth.password (required) PostgreSQL DB user password (base64 encoded)
    password: ""
    # secret.auth.hdfsUser (required) HDFS user (base64 encoded)
    hdfsUser: ""

# all sudo as root to enable modification on /etc/hosts
securityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: true

# settings of entrypoint.sh args
entrypoint:
  sleep: 60
  csvCounts: 10
