# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-evam-ingress
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: evam
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: {{ .Values.config.edge_video_analytics_microservice.rest_api_port.int_port }}
    - port: {{ .Values.config.edge_video_analytics_microservice.rtsp_port.int_port }}      
