# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
{{- if .Values.global.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace.value }}
{{ if .Values.global.namespace.istioInjection.create }}
  labels:
    istio-injection: enabled
{{ end }}
{{- end -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evi-spark-cluster
  namespace: {{ .Values.global.namespace.value }}
  labels:
    version: v1
  annotations:
    container.apparmor.security.beta.kubernetes.io/spark-cluster: runtime/default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-cluster
      version: v1
  template:
    metadata:
      labels:
        app: spark-cluster
        sidecar.istio.io/inject: "{{ .Values.istioInjection }}"
        version: v1
    spec:
      nodeSelector:
        feature.node.kubernetes.io/cpu-cpuid.AVX512VNNI: 'true'
        feature.node.kubernetes.io/cpu-cpuid.AVX2: 'true'
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      #- name: spark-cluster
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        #- containerPort: 8088
        - containerPort: {{ .Values.image.port }}
        resources:
          limits:
            cpu: "64"
            memory: 100Gi
          requests:
            cpu: "32"
            memory: 30Gi
        volumeMounts:
        - name: {{ .Values.volumes.name }}
          readOnly: {{ .Values.volumes.readOnly }}
          mountPath: "{{ .Values.volumes.mountPath }}"
        - name: spark-cluster-cm-volume
          mountPath: "/opt/configure"
        securityContext:
          # readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
      volumes:
      - name: {{ .Values.volumes.name }}
        secret:
          secretName: {{ .Values.secret.secretName }}
      - name: spark-cluster-cm-volume
        configMap:
          name: {{ .Values.configMap.name }}
