apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: influxdb-abcxzy
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb
      app.kubernetes.io/instance: influxdb-abcxzy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: influxdb
        app.kubernetes.io/instance: influxdb-abcxzy
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name}}
      serviceAccount: {{ .Values.serviceAccount.name}}
      containers:
        - name: {{ .Chart.Name}}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: persistent
              mountPath: /var/lib/influxdb
      volumes:
        - name: persistent
          persistentVolumeClaim:
            claimName: influxdb
