apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: influxdb-abcxzy
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: helm
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: influxdb-abcxzy
