# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
address: serviceAddress:servicePort
root:    disabled  # We disable the root identity since we don't need it in this guide 

tls:
  key:  /pki/kes-server.key
  cert: /pki/kes-server.crt

policy:    
  minio: 
    paths:
    - /v1/key/create/minio-*
    - /v1/key/generate/minio-*
    - /v1/key/decrypt/minio-*
    - /v1/key/list/minio-*
    identities:
    - ${APP_IDENTITY}

cache:
  expiry:
    any:    5m0s 
    unused: 20s

log:
  error: on
  audit: on

keys:
  vault:
    endpoint: https://vaulteServiceAddress:vaulteServicePort
    prefix: minio
    approle:
      id: ${APP_ROLE_ID} # Your AppRole ID
      secret: ${APP_SECRET_ID} # Your AppRole Secret ID
      retry:  15s
    status:
      ping: 10s
    tls:
      ca: "/pki/vault-server.crt" # Since we use self-signed certificates
