# INTEL CONFIDENTIAL
#
# Copyright (C) 2022-2023 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: evi-postgresql-pv0
spec:
  capacity:
    storage: {{ .Values.persistance.size }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.global.storageClass }}
  local:
    path: {{ required "A valid persistance.basePath is required!" .Values.persistance.basePath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ required "A valid persistance.hostname is required!" .Values.persistance.hostname }}

{{- if eq .Values.postgresql.architecture "replication" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: evi-postgresql-pv1
spec:
  capacity:
    storage: {{ .Values.persistance.size }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.global.storageClass }}
  local:
    path: {{ .Values.persistance.basePath }}_{{ .Values.postgresql.architecture }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.persistance.replication.hostname }}
{{- end }}
