# Copyright 2022 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.rule_engine.name }}
  name: {{ .Values.rule_engine.name }}
  namespace: {{ .Values.namespace }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rule_engine.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.rule_engine.name }}
        role: itm
    spec:
      containers:
      - name: {{ .Values.rule_engine.name }}
        image: {{ .Values.images.registry }}{{ .Values.images.rule_engine }}:{{ .Values.images.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        volumeMounts:
        - name: cm-cfg
          mountPath: /app/config.json
          subPath: config.json
          readOnly: true
        - name: cm-cfg
          mountPath: /app/schema.json
          subPath: schema.json
          readOnly: true
        env:
        {{- $minval :=  int 1 -}}
        {{- $maxval :=  int .Values.num_video_instances | add1 | int -}}
        {{- $topic := .Values.itm_analytics.topic.publisher -}}
        {{- $topics := list -}}
        {{- range untilStep $minval $maxval 1 -}}
        {{- $topics = printf "%s%d" $topic . | append $topics -}}
        {{- end }}
        - name: SUBSCRIBER_TOPIC
          value: {{ $topics | join " " }}
        - name: PUBLISHER_TOPIC
          value: {{ .Values.rule_engine.topic.publisher }}
        - name: MQTT_PORT
          value: "{{ .Values.mqtt.port }}"
        - name: MQTT_BROKER
          value: {{ .Values.mqtt.broker }}
        - name: PY_LOG_LEVEL
          value: "{{ .Values.py_log_level }}"
        - name: NUM_VIDEO_INSTANCES
          value: "{{ .Values.num_video_instances }}"
        securityContext:
          readOnlyRootFilesystem: true
      volumes:
      - name: cm-cfg
        configMap:
          name: rule-engine-config
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"