apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "intel-gaudi-resource-driver.clusterRoleName" . }}
  namespace: {{ include "intel-gaudi-resource-driver.namespace" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "events"]
  verbs: ["get", "list", "create", "watch", "patch"]
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceclaims", "resourceclasses", "podschedulings","resourceclaims/status", "podschedulings/status", "podschedulingcontexts", "podschedulingcontexts/status"]
  verbs: ["get", "update", "list", "watch", "patch"]
- apiGroups: ["gaudi.resource.intel.com"]
  resources: ["*"]
  verbs: ["*"]