apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClass
metadata:
  name: intel-gaudi
driverName: gaudi.resource.intel.com
parametersRef:
  apiGroup: gaudi.resource.intel.com/v1alpha1
  kind: GaudiClassParameters
  name: intel-gaudi-params
---
apiVersion: gaudi.resource.intel.com/v1alpha1
kind: GaudiClassParameters
metadata:
  name: intel-gaudi-monitor-params
spec:
  monitor: true
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClass
metadata:
  name: intel-gaudi-monitor
driverName: gaudi.resource.intel.com
parametersRef:
  apiGroup: gaudi.resource.intel.com/v1alpha1
  kind: GaudiClassParameters
  name: intel-gaudi-monitor-params
