apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gaudi-resource-driver-kubelet-plugin
  namespace: {{ include "intel-gaudi-resource-driver.namespace" . }}
  labels:
    {{- include "intel-gaudi-resource-driver.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
     app: intel-gaudi-resource-driver-kubelet-plugin
  template:
    metadata:
      labels:
        app: intel-gaudi-resource-driver-kubelet-plugin
    spec:
      serviceAccount: intel-gaudi-resource-driver-service-account
      serviceAccountName: {{ include "intel-gaudi-resource-driver.serviceAccountName" . }}
      initContainers:
      - name: init
        image: {{ include "intel-gaudi-resource-driver.fullimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/kubelet-gaudi-plugin", "--status", "NotReady"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10002
          seccompProfile:
            type: RuntimeDefault
      containers:
      - name: kubelet-plugin
        image: {{ include "intel-gaudi-resource-driver.fullimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/kubelet-gaudi-plugin"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SYSFS_ROOT
          value: "/sysfs"
        # Use this to tell kubelet-plugin where the DRI devices nodes should be.
        # This will be prefix for CDI devices, runtime will try to mount devices
        # with this prefix into workloads.
        #- name: DEV_DRI_PATH
        #  value: "/fake/dri"
        volumeMounts:
        - name: plugins-registry
          mountPath: /var/lib/kubelet/plugins_registry
        - name: plugins
          mountPath: /var/lib/kubelet/plugins
        - name: cdi
          mountPath: /etc/cdi
        - name: varruncdi
          mountPath: /var/run/cdi
        - name: sysfs
          mountPath: "/sysfs"
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
          runAsUser: 0
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: plugins-registry
        hostPath:
          path: /var/lib/kubelet/plugins_registry
      - name: plugins
        hostPath:
          path: /var/lib/kubelet/plugins
      - name: cdi
        hostPath:
          path: /etc/cdi
      - name: varruncdi
        hostPath:
          path: /var/run/cdi
      - name: sysfs
        hostPath:
          path: /sys
      {{- with .Values.kubeletPlugin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeletPlugin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeletPlugin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intel-gaudi-resource-driver-controller
  namespace: {{ include "intel-gaudi-resource-driver.namespace" . }}
  labels:
     {{- include "intel-gaudi-resource-driver.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intel-gaudi-resource-driver-controller
  template:
    metadata:
      labels:
        app: intel-gaudi-resource-driver-controller
    spec:
      serviceAccount: intel-gaudi-resource-driver-service-account
      serviceAccountName: {{ include "intel-gaudi-resource-driver.serviceAccountName" . }}
      containers:
      - name: controller
        image: {{ include "intel-gaudi-resource-driver.fullimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/gaudi-controller"]
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10002
          seccompProfile:
            type: RuntimeDefault
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
