iaa:
  metadata:
    name: iaadeviceplugin-sample
  spec:
    image: intel/intel-iaa-plugin:0.24.0
    sharedDevNum: 10
    logLevel: 4
    nodeSelector:
      intel.feature.node.kubernetes.io/iaa: 'true'