apiVersion: v2
name: intel-gpu-resource-driver
description: A Helm chart for a Dynamic Resource Allocation (DRA) Intel GPU Resource Driver

type: application
version: 0.7.0
appVersion: "v0.7.0"
home: https://github.com/intel/helm-charts

dependencies:
  - name: node-feature-discovery
    alias: nfd
    version: "0.16.6"
    condition: nfd.enabled
    repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
