# Default values for intel-gpu-resource-driver.
nameOverride: ""
namespaceOverride: "intel-gpu-resource-driver"
fullnameOverride: ""
selectorLabelsOverride: {}

imagePullSecrets: []
image:
  repository: intel
  name: intel-gpu-resource-driver
  pullPolicy: IfNotPresent
  tag: "v0.6.0"

serviceAccount:
  create: true
  annotations: {}
  name: intel-gpu-resource-driver-service-account
  automount: true

kubeletPlugin:
  podAnnotations: {}
  tolerations: []
  nodeSelector: {}
  affinity: {}
