apiVersion: v1
appVersion: v1.4.1
description: Uses fluent-bit Loki go plugin for gathering logs and sending them to
  Loki
home: https://grafana.com/loki
icon: https://github.com/grafana/loki/raw/master/docs/logo.png
kubeVersion: ^1.10.0-0
maintainers:
- email: lokiproject@googlegroups.com
  name: Loki Maintainers
name: fluent-bit
sources:
- https://github.com/grafana/loki
version: 0.1.1
