{{- if .Values.prometheus.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "hbase.fullname" . }}-region-metrics
  labels:
    app.kubernetes.io/name: {{ include "hbase.name" . }}
    app.kubernetes.io/component: regionserver
    {{- include "hbase.labels" . | nindent 4 }}
spec: 
  selector: 
    app.kubernetes.io/name: {{ include "hbase.name" . }}
    app.kubernetes.io/component: regionserver
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: {{ .Values.prometheus.port }}
    name: metrics
    targetPort: {{ .Values.prometheus.port }}
{{- end -}}