# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace.value }}
  name: {{ .Values.configMap.name }}
data:
  app.config: |
    AI_SERVICE = "{{ .Values.configMap.aiInference.addr }}"
    AI_PORT = "{{ .Values.configMap.aiInference.port }}"
    STORAGE_SERVICE = "{{ .Values.configMap.storageRest.addr }}"
    STORAGE_PORT = "{{ .Values.configMap.storageRest.port }}"
    RTSP_SERVICE = "{{ .Values.configMap.rtspService.addr }}"
    RTSP_PORT = "{{ .Values.configMap.rtspService.port }}"
    RTSP_SERVICE_COUNT = "{{ .Values.configMap.rtspServiceCount }}"
    CLUSTER_SERVICE =  "{{ .Values.configMap.clusterService.addr }}"
    CLUSTER_PORT =   "{{ .Values.configMap.clusterService.port }}"
