{
 "title": "Multi Camera Covid-19 Solution",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Current People Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Current People Count",
     "measurement": "people_count",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Social Violations",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total Social Violations",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 1",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "0" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 2",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 3",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "2" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 4",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "3" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 5",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "4" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 6",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "5" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 7",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "6" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 8",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "7" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 9",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "8" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 10",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "9" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 11",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "10" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 12",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "11" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 13",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "12" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 14",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "13" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 15",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "14" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 16",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "15" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Social Violations Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "alias": "Total Social Violations",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 1",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "0" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 2",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 3",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "2" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 4",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "3" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 5",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "4" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 6",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "5" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 7",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "6" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 8",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "7" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 9",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "8" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 10",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "9" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 11",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "10" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 12",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "11" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 13",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "12" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 14",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "13" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 15",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "14" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 16",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "15" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Social Dist. Violations",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "Current Social Dist. Violations",
     "measurement": "social_distancing_violations",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mask Violations",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 3, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total Mask Violations",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 1",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "0" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 2",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 3",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "2" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 4",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "3" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 5",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "4" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 6",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "5" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 7",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "6" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 8",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "7" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 9",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "8" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 10",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "9" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 11",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "10" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 12",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "11" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 13",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "12" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 14",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "13" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 15",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "14" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 16",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "15" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mask Violations Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 11 },
   "targets": [
    {
     "alias": "Total Mask Violations",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 1",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "0" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 2",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 3",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "2" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 4",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "3" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 5",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "4" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 6",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "5" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 7",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "6" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 8",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "7" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 9",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "8" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 10",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "9" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 11",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "10" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 12",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "11" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 13",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "12" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 14",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "13" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 15",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "14" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Channel 16",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "15" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Mask Violations",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "Current Mask Violations",
     "measurement": "mask_violation",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}