sgx:
  metadata:
    name: sgxdeviceplugin-sample
  spec:
    image: intel/intel-sgx-plugin:0.24.0
    initImage: intel/intel-sgx-initcontainer:0.24.0
    enclaveLimit: 110
    provisionLimit: 110
    logLevel: 4
    nodeSelector:
      intel.feature.node.kubernetes.io/sgx: 'true'
