# Copyright (c) 2021 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.etcd_ui.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: etcd-ui
  ports:
  - port: {{ .Values.config.etcd_ui.int_port }}
    targetPort: {{ .Values.config.etcd_ui.int_port }}
    nodePort: {{ .Values.config.etcd_ui.ext_port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etcd-ui
  name: deployment-etcd-ui
  namespace: {{ .Values.namespace }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-ui
  template:
    metadata:
      labels:
        app: etcd-ui
    spec:
      nodeSelector:
        feature.node.kubernetes.io/system-os_release.ID: "ubuntu"
      {{- if and .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD }}
      imagePullSecrets:
      - name: registryauth
      {{- end }}
      containers:
      - name: ia-etcd-ui
        image: {{ .Values.DOCKER_REGISTRY }}openedgeinsights/ia_etcd_ui:{{ .Values.EII_VERSION }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        volumeMounts:
        - name: tmp-ssl
          mountPath: "/opt/nginx"
        {{ if eq .Values.env.DEV_MODE false}}
        - name: etcd-certs
          mountPath: /run/secrets/etcd/
        {{ end }}
        env:
        - name: AppName
          value: "EtcdUI"
        - name: DEV_MODE
          value: '{{ .Values.env.DEV_MODE }}'
        - name: NGINX_PORT
          value: "{{ .Values.config.etcd_ui.int_port }}"
        - name: ETCD_HOST
          value: {{ .Values.config.etcd.name }}
        - name: ETCD_CLIENT_PORT
          value: '{{ .Values.config.etcd.client_port }}'
        - name: PROVISION_MODE
          value: ''
        - name: ETCD_PREFIX
          value: ''
        - name: ETCD_ENDPOINT
          value: '{{ .Values.config.etcd.name }}:{{ .Values.config.etcd.client_port }}'
        - name: ETCD_USER
          value: "root"
        {{ if eq .Values.env.DEV_MODE false}}
        - name: CONFIGMGR_CACERT
          value: "/run/secrets/etcd/cacert.pem"
        - name: CONFIGMGR_CERT
          value: "/run/secrets/etcd/EtcdUI_client_certificate.pem"
        - name: CONFIGMGR_KEY
          value: "/run/secrets/etcd/EtcdUI_client_key.pem"
        {{ end }}
      volumes:
      - name: tmp-ssl
        emptyDir:
          medium: Memory
      {{ if eq .Values.env.DEV_MODE false}}
      - name: etcd-certs
        secret:
          secretName: eii-certs
          items:
          - key: cacert.pem
            path: cacert.pem
          - key: EtcdUI_client_certificate.pem
            path: EtcdUI_client_certificate.pem
          - key: EtcdUI_client_key.pem
            path: EtcdUI_client_key.pem
      {{ end }}
