# Copyright (c) 2021 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

{{ if eq .Values.env.DEV_MODE false}}

apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: eii-certs
data:
  {{- (.Files.Glob "Certificates/**.pem").AsSecrets | nindent 2 }}
  {{- (.Files.Glob "Certificates/**.der").AsSecrets | nindent 2 }}

{{ end }}
---
{{- if and .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD }}
apiVersion: v1
kind: Secret
metadata:
  name: registryauth
  namespace: {{ .Values.namespace }}
data:
  {{- if .Values.DOCKER_REGISTRY }}
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.DOCKER_REGISTRY (printf "%s:%s" .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD | b64enc) | b64enc }}
  {{- else }}
  .dockerconfigjson: {{ printf "{\"auths\": {\"https://index.docker.io/v1/\": {\"auth\": \"%s\"}}}" (printf "%s:%s" .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD | b64enc) | b64enc }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
{{- end }}
